### ISSUE TITLE
how to manage "autoswitch"?

### ISSUE THREAD

**Issue by taxen** [nohamelin/simple-locale-switcher#17]
There is no way to add or edit but just delete "autoswitch" site setting.
Is there any way?

I just wonder this feature is useful when I prefer language A on site X and language B on site Y.
Based on my demand, I want to put X (lang: A) and Y (lang:B) on the tab.

But other than that I wrongfully deleted the default chrome something URL from the list, I cannot do anything.

I have tested both 0.0.1 and 0.0.2.6.

**Comment by nohamelin** [comment]
Hi,
Aren't you mixing this tracker with another one by mistake? There isn't any autoswitch setting in my add-on, and I don't recognize that version numbers...

**Comment by taxen** [comment]
Uh, yes... I came here from the link https://github.com/nohamelin/simple-locale-switcher/issues/16 included in https://addons.mozilla.org/ja/firefox/addon/quick-locale-switcher-2/
Sorry!
